version: '3'
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    volumes:
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports: 
      - '8080:80'
    restart: always
  api:
    build:
      dockerfile: Dockerfile
      context: ./api
    volumes:
      - /app/node_modules
      - ./api:/app
    ports:
      - '3000:3000'
    restart: always
  redis:
    image: redis
    volumes: 
      - /tmp/redis/data:/data
    restart: always
    ports:
      - 6379:6379
  postgres:
    image: postgres
    volumes: 
      - /tmp/postgres/data:/var/lib/postgresql/data
    restart: always
    ports: 
      - 5432:5432
  