version: '3'
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    volumes:
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports: 
      - '8080:80'
  api:
    build:
      dockerfile: Dockerfile
      context: ./api
    volumes:
      - /app/node_modules
      - ./api:/app
    ports:
      - '3000:3000'